### ISSUE TITLE
about defend method

### ISSUE THREAD

**Issue by zxk19981227** [thunlp/HiddenKiller#3]
To syntactic defend method, is there any code that released?

**Comment by Yangyi-Chen** [comment]
Thanks for watching! 
For ONION defense method, pls refer to [this repo](https://github.com/thunlp/ONION);
For sentence-level defense methods, there are no relevant codes released because the implementation is quite intuitive. For the back-translation-based defense method, we employ the official google translator to transform the sentences and reevaluate the attack success rate and clean accuracy; For the syntactic-based defense method, we employ SCPN to transform the sentence.
